### ISSUE TITLE
Manually migrate 2019 Operational Bulletin data

### ISSUE THREAD

**Issue by ronaldtse** [ituob/itu-ob-data#1]
I've converted number 1173 for a trial.

**Comment by strogonoff** [comment]
I believe we’re close to having a complete YAML representation in #5, and from that will be able to generate consistent AsciiDoc (and directly HTML) with some use of templating.

**Comment by strogonoff** [comment]
Manual migration steps

(for reference)

Pre-requisites:

Install reverse_asciidoctor (https://www.metanorma.com/software/reverse_asciidoctor/) and LibreOffice
to ensure w2a binary is available.

Steps for each issue:

1. Create directory inside local fork of itu-ob-data: `itu-ob-data/issues/<issue ID>/`

    Where issue ID is e.g. “1171”.

2. Copy meta.yaml from some existing issue into new `<issue ID>/meta.yaml`

    2a. Fill in publication_date and cutoff_date from the reference .docx into newly created meta.yaml

3. Create `<issue ID>/general.yaml`

    3a. For each message in “General” section of the reference doc, add an item into “messages” array in general.yaml, for example:

    ```
    messages:

    - type: <message type>
      <message properties>
    ```

    Where `<message type>` is one of the types specified in https://github.com/ituob/ituob.org/blob/master/_config.yml#L10, except “amendment” type (it is unused in general.yaml section).

    The exact `<message properties>` depends on message type. Use existing issues for reference. Most typically it is `“contents: <relative path to .adoc file>”`

4. Create `<issue ID>/amendments.yaml`

    4a. For each message in the “Amendments” section of the reference doc, add an item into “messages” array in amendments.yaml, for example:

    ```
    messages:

    - type: amendment
      target:
        publication: <publication code>
        position_on: <month or year>
      contents: amendments/<publication code>.adoc
    ```

    Where `<publication code>` references the publication being amended.

    4b. If publication amended does not exist under itu-ob-data/lists, create a directory for it with meta.yaml inside. Use existing publication for an example of meta.yaml.

    4c. Most publications refer to recommendations. If recommendation does not exist under itu-ob-data/recommendations, create a directory for it with meta.yaml inside. Use existing recommendation for an example.

5. Convert the reference .docx into temporary AsciiDoc file:

    ```
    $ w2a [path to original .docx file] > [path to temporary .adoc file]
    ```

6. For each message in general.yaml and amendments.yaml, where the type requires `“contents: <relative-path>.adoc”`, create appropriate .adoc file inside `itu-ob-data/<issue ID>/[amendments | general]/`. Copy message contents (excluding header) from the temporary .adoc file into the new message contents file and clean up markup.

**Comment by strogonoff** [comment]
1171 remains to be finished later, AsciiDoc markup for large complex tables in telephone service in this particular case will take a long time for me personally.

**Comment by strogonoff** [comment]
We have 2019 issues up to 1174 so I am closing this, instead of playing catch-up with later issues we can handle them in a different milestone.
