### ISSUE TITLE
Will NNP communications be translated into supported languages?

### ISSUE THREAD

**Issue by strogonoff** [ituob/itu-ob-data#10]
Currently, an OB issue includes communications from countries/geographical areas about numbering schema changes.

* Are these communications provided in English originally, or translated to English by ITU?
* Will these communications be translated to other 6 languages? or, presented only in English? or, presented only in English and in their original language (where different from English)?

**Comment by ronaldtse** [comment]
Good question. Preliminary answer:

> Are these communications provided in English originally, or translated to English by ITU?

I believe English only. The rest 5 languages are translated by ITU. I will confirm.

> Will these communications be translated to other 6 languages? or, presented only in English? or, presented only in English and in their original language (where different from English)?

All communications are translated to all 6 languages. For example, the OB 1170 is translated to Russian here: https://www.itu.int/dms_pub/itu-t/opb/sp/T-SP-OB.1170-2019-OAS-PDF-R.pdf

**Comment by strogonoff** [comment]
Got it, for some reason I thought OB is only planning to be translated into other languages, but apparently it’s only down to us to maintain localization in our UIs.
