### ISSUE TITLE
Fix trigger deploy of ituob.org website

### ISSUE THREAD

**Issue by ronaldtse** [ituob/itu-ob-data#112]
Following #83 the trigger workflow code is now updated.

@CAMOBAP can you please help fix the trigger to trigger this workflow? Thanks!

* https://github.com/ituob/ituob.org/blob/main/.github/workflows/build_deploy.yml

**Comment by CAMOBAP** [comment]
The original issue is fixed by removing `--exclude-files` but there still some issues left:
- malformed email (like: `firmapost@npt.no` and `info@dena-aria.com`)
- external links (like `www.itu.int/ITU-T/inr/roa/index.html`) aren't validated correctly

For some reason HTML generated with spaces in href like this
```
<a href="
--
  |  
  | /issues/955-en
  |  
  | ">
  |  
  |  
  | 955
  |  
  |  
  | </a>


```

Investigtion in progress

**Comment by CAMOBAP** [comment]
I have missed the original issue) The trigger is working https://github.com/ituob/ituob.org/actions/runs/4359123095

BTW here are top link issues:
  31 [403] [https://kit.fontawesome.com/3ebc4b9810.js](https://kit.fontawesome.com/3ebc4b9810.js) | Failed: Network error: Forbidden
  39 [ERR] [https://www.itu.int/pub/T-SP-E.164B-2012](https://www.itu.int/pub/T-SP-E.164B-2012) | Cached: Error (cached)
  88 [ERR] [http://www.itu.int/pub/T-SP-SR.1-2012](http://www.itu.int/pub/T-SP-SR.1-2012) | Cached: Error (cached)
 123 [ERR] [https://www.itu.int/pub/T-SP-Q.708A-2013](https://www.itu.int/pub/T-SP-Q.708A-2013) | Cached: Error (cached)
 214 [ERR] [https://www.itu.int/pub/T-SP-Q.708B](https://www.itu.int/pub/T-SP-Q.708B) | Cached: Error (cached)
 234 [ERR] [http://www.itu.int/pub/T-SP-PP.RES.21-2011/](http://www.itu.int/pub/T-SP-PP.RES.21-2011/) | Cached: Error (cached)
 273 [ERR] [https://www.itu.int/pub/T-SP-OB.669-1998](https://www.itu.int/pub/T-SP-OB.669-1998) | Cached: Error (cached)
 297 [404] [http://www.itu.int/itu-t/inr/nnp/index.html](http://www.itu.int/itu-t/inr/nnp/index.html) | Cached: Error (cached)
 301 [404] [https://www.itu.int/itu-t/bulletin/](https://www.itu.int/itu-t/bulletin/) | Cached: Error (cached)
 304 [404] [http://www.itu.int/itu-t/inr-nnp](http://www.itu.int/itu-t/inr-nnp) | Cached: Error (cached)
 615 [403] [https://kit.fontawesome.com/3ebc4b9810.js](https://kit.fontawesome.com/3ebc4b9810.js) | Cached: Error (cached)

And the full list just in case [err-stat.log](https://github.com/ituob/itu-ob-data/files/10914416/err-stat.log)

Maybe we should report another issue to improve it in future

**Comment by ronaldtse** [comment]
## Will be fixed

> 297 [404] http://www.itu.int/itu-t/inr/nnp/index.html | Cached: Error (cached)

This is in the original data.

> 301 [404] https://www.itu.int/itu-t/bulletin/ | Cached: Error (cached)

This link exists in OB Issue 956

## Working links

These links are all working for me:

39 [ERR] https://www.itu.int/pub/T-SP-E.164B-2012 | Cached: Error (cached)
88 [ERR] http://www.itu.int/pub/T-SP-SR.1-2012 | Cached: Error (cached)
123 [ERR] https://www.itu.int/pub/T-SP-Q.708A-2013 | Cached: Error (cached)
214 [ERR] https://www.itu.int/pub/T-SP-Q.708B | Cached: Error (cached)
234 [ERR] http://www.itu.int/pub/T-SP-PP.RES.21-2011/ | Cached: Error (cached)
273 [ERR] https://www.itu.int/pub/T-SP-OB.669-1998 | Cached: Error (cached)

## Next steps

Can you help with these additional tasks?

* [ ] Verify that failure in link checks does not block deployment (I think we are not blocking)
* [ ] Make the lychee link checker skip email validation, too many are failing (should we do this?)

What other steps?

**Comment by CAMOBAP** [comment]
For email I already moved validation to another step an mark it optional, I propose to keep it optional

Also, we are able to ignore specific links (via CLI or by providing config)

> These links are all working for me

For me too it reports "Cached: Error (cached)" maybe make sense to drop the cache and look on up-to-date report

**Comment by ronaldtse** [comment]
> drop the cache and look on up-to-date report

I do agree but maybe there are too many links to check and it takes too long?

**Comment by ronaldtse** [comment]
This is all done, thank you @CAMOBAP !
