### ISSUE TITLE
Rebuild ituob.org after data repo is updated

### ISSUE THREAD

**Issue by strogonoff** [ituob/itu-ob-data#18]
There is now a minimal [.travis.yml](https://github.com/ituob/itu-ob-data/blob/master/.travis.yml) here that works similarly to Metanorma.com. It’s supposed to trigger ituob.org build when something is pushed to itu-ob-data master.

@ronaldtse, could you please help with CI setup on itu-ob-data? Namely, we need to ensure the repo is enabled in Travis, and `$TRAVIS_ACCESS_TOKEN` environment variable is set. The token can be obtained by running `travis token --com` (requires Travis CLI gem installed, `--com` should be `--org` if we’re using travis-ci.org).

**Comment by ronaldtse** [comment]
@strogonoff the token has been filled at the job and I’ve manually tried the triggering.

**Comment by strogonoff** [comment]
Just had a chance to test it by pushing a change to issue 1171 (https://github.com/ituob/itu-ob-data/commit/614ea16776b555b4fd68049918d79f2f41c4f261), it seems like this did not trigger site build… `.travis.yml` in this repository will have to be checked later, I may not have ported this solution properly.

**Comment by ronaldtse** [comment]
@strogonoff the build failed https://travis-ci.com/ituob/itu-ob-data

Could you help add the Travis badge to the README? Thanks 😉

**Comment by strogonoff** [comment]
yeah the fact that the build failed was kind of my point…😂

**Comment by strogonoff** [comment]
@ronaldtse site build trigger reports “access denied”, which makes me think the access token is not correct. I’m going to try replacing it with a token I generate from my account, but I don’t know if it’ll work since this is under `ituob` org.

**Comment by strogonoff** [comment]
Woohoo, I think my access token was enough. Closing!

**Comment by strogonoff** [comment]
Travis badge added for this repo and ituob.org.

**Comment by ronaldtse** [comment]
Thanks @strogonoff ! I've also switched the build account to @ituob-ci so the triggered builds can be differentiated from  your own builds.
