### ISSUE TITLE
Determine the scope of ITU OB issue archive processing

### ISSUE THREAD

**Issue by strogonoff** [ituob/itu-ob-data#20]
* The oldest issue available through itu.int archive is 567 from 1994. Is there a resource for older issues? Are we expected to migrate them as well?

* Older ITU OB issues are in .doc format, not .docx:  https://www.itu.int/dms_pub/itu-t/opb/sp/T-SP-OB.567-1994-MSW-E.doc

    * They are not available in PDF either.

    * .doc format is used at least until 2007. As of 2011, issues are in .docx. Annexes are still in .doc (but we are unlikely to need to parse the contents of each annex).

    * There are tools (in Ruby as well) that can extract contents from .doc, but they are more limited. Migrating legacy issues may require more effort. Is it worth it?

This is primarily a question to @ronaldtse

**Comment by strogonoff** [comment]
The decision on whether to port older issues may determine the approach for migration—if we have to migrate older issues and cannot parse .doc well automatically (extracting tabular data is a big one here), we may choose a semi-automated migration process that relies on human input to separate messages within one issue.

**Comment by strogonoff** [comment]
According to @ronaldtse we shall process issues only as far back as .docx goes, as part of milestone https://github.com/ituob/itu-ob-data/milestone/2.

**Comment by ronaldtse** [comment]
Thanks @strogonoff for filing this. At this point we won't deal with the `.doc` files. As long as we ca process the `.docx` files, we're good.

**Comment by strogonoff** [comment]
Looking ahead to next milestones it seems we’ll have potentially two or three migration mechanisms:

1. Automated .docx processing for most recent 2–3 hundred issues,
2. Semi-automatic for older .doc files (whether with OCR or another approach),
3. Obtaining issues older than 576 from another resource than itu.int and processing whatever format they’re in.

We’ll deal with only (1) as part of this milestone.

In case our initial experiments prove it impossible to process .docx contents automatically due to complex formatting (primarily, complicated tables), we should scrap that approach in favor of a human-based assisted migration tool and use it to migrate all of the archives (potentially, inviting a third-party data entry staff).
