### ISSUE TITLE
Some data missing across OB issues

### ISSUE THREAD

**Issue by ronaldtse** [ituob/itu-ob-data#22]
* "Lists annexed to the ITU Operational Bulletin"
* "Approval of ITU-T Recommendations”

Are both incomplete as we are finding ways to better model them.

**Comment by strogonoff** [comment]
I don’t see obvious issues with the existing model. The migration is pending. First item is a duplicate of #21, and for second item I created https://github.com/ituob/ituob.org/issues/13.
