### ISSUE TITLE
Migrate repo to trigger GHA (instead of Travis)

### ISSUE THREAD

**Issue by ronaldtse** [ituob/itu-ob-data#43]
This repo currently triggers a "travis build" to deploy www.ituob.org, but we're no longer using Travis.

We need to migrate this repo to a trigger the GHA deploy flow of https://github.com/ituob/ituob.org .

**Comment by CAMOBAP** [comment]
@ronaldtse `secrets.PAT_TOKEN` need to be added ?

**Comment by ronaldtse** [comment]
Added `secrets.ITUOB_CI_GHA_TOKEN` for all repos.

**Comment by ronaldtse** [comment]
Done, closing.
